apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: git-command
  annotations:
    workflows.argoproj.io/description: |
      Checkout out from Git, build and test a Golang application.
    workflows.argoproj.io/maintainer: '@alexec'
    workflows.argoproj.io/tags: golang, git
    workflows.argoproj.io/version: '>= 2.9.0'
spec:
  templates:
    - name: clone
      inputs:
        parameters:
          - name: REPO_URL
          - name: REVISION
            default: main
          - name: GIT_TOKEN_SECRET
          - name: GIT_USERNAME
            default: token
      script:
        image: alpine/git
        env:
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: '{{inputs.parameters.GIT_TOKEN_SECRET}}'
                key: token
          - name: GIT_USERNAME
            value: '{{ inputs.parameters.GIT_USERNAME }}'
        command: [ bash ]
        source: |
          REPO_URL="{{inputs.parameters.REPO_URL}}"
          REVISION="{{inputs.parameters.REVISION}}"
          DIRPATH="{{ outputs.artifacts.repo.path }}"
          echo "inputs REPO_URL:$REPO_URL REVISION:$REVISION DIRPATH:$DIRPATH"
          mkdir -p $DIRPATH && cd $DIRPATH
          PATTERN="https://" && CHANGE="https://$GIT_USERNAME:$TOKEN@" && TOKEN_REPO="${REPO_URL/$PATTERN/"$CHANGE"}"
          git clone $TOKEN_REPO $DIRPATH -b $REVISION
      outputs:
        artifacts:
          - name: repo
            path: /git/repo